setwd("/group/bprice5")
dat<-read.csv("1314C-08.CSV", header=TRUE)

```{r setup, include=FALSE}
chooseCRANmirror(graphics=FALSE, ind=1)
knitr::opts_chunk$set(echo = TRUE)
install.packages("alr4")
library(alr4)
help("1314C-08.CSV")
```

t.test(dat$FED.PELL.GRANT)
t.test(dat$FED.SUPPL.ED.OPP)
t.test(dat$OTHER.FED.GRANTS.AND.SCHOLARS)
t.test(dat$WV.HIGHER.ED.GRANT.PROG)
t.test(dat$PROMISE.SCHOLARS)
t.test(dat$OTHER.WV.STATE.GRANTS.AND.SCHOLARS)
t.test(dat$MISC.GRANTS.AND.SCHOLARS)
t.test(dat$PROC..RULE.NO..49.UG.TUI.FEE.WAIV.ATHL)
t.test(dat$PROC..RULE.NO..49.UG.TUI.FEE.WAIV.ACAD)
t.test(dat$PROC..RULE.NO..49.UG.TUI.FEE.WAIV.NEED...OTHER)
t.test(dat$PROC..RULE.NO..49.GR...PR.TUI.FEE.WAIVS)
t.test(dat$INST.GRANTS.AND.SCHOLARS.ATHLETIC)
t.test(dat$INST.GRANTS.AND.SCHOLARS.ACADEMIC)
t.test(dat$INST.GRANTS.AND.SCHOLARS.OTHER)
t.test(dat$INST.EMPLOYMENT)
t.test(dat$FED.DIRECT.LOAN....SUBSIDIZED)
t.test(dat$FED.DIRECT.LOAN....UNSUBSIDIZED)
t.test(dat$FED.DIRECT.PLUS)
t.test(dat$OTHER.FED.LOANS)
t.test(dat$MED.STUDENT.LOAN)
t.test(dat$OUT.OF.STATE.GRANTS.AND.SCHOLARS)
